#include "network.h++"
#include "enum.h++"
#include "meme.h++"
#include "lex.h++"
#include "agent.h++"
#include "language.h++"
#include "enumvector.h++"
#include "counts.h++"
#include "selfiterator.h++"
#include <cmath>
#include <iostream>
#include <iterator>
#include <random>
